export const GAME_WIDTH = 1380;
export const GAME_HEIGHT = 780;
export const BLOCK_SIZE = 30;

const blocksMap = new Map();
blocksMap.set('t',{imageName: 'trunk', hasCollider: true});
blocksMap.set('b',{imageName: 'brick', hasCollider: true});
blocksMap.set('s',{imageName: 'stone0', hasCollider: true});
blocksMap.set('d',{imageName: 'dirt', hasCollider: true});
blocksMap.set('#',{imageName: 'empty', hasCollider: false});
blocksMap.set('2',{imageName: 'stone_top', hasCollider: true});
blocksMap.set('1',{imageName: 'stone_left', hasCollider: true});
blocksMap.set('3',{imageName: 'stone_right', hasCollider: true});
blocksMap.set('4',{imageName: 'floor1', hasCollider: true});
blocksMap.set('5',{imageName: 'floor2', hasCollider: true});
blocksMap.set('6',{imageName: 'grass1', hasCollider: false});
blocksMap.set('7',{imageName: 'grass2', hasCollider: false});
blocksMap.set('8',{imageName: 'leafs', hasCollider: false});
blocksMap.set('9',{imageName: 'stone1', hasCollider: true});
blocksMap.set('@',{imageName: 'stone2', hasCollider: true});
blocksMap.set('!',{imageName: 'door1', hasCollider: false});
blocksMap.set('$',{imageName: 'door2', hasCollider: false});
blocksMap.set('%',{imageName: 'door3', hasCollider: false});
blocksMap.set('(',{imageName: 'sand0', hasCollider: true});
blocksMap.set('^',{imageName: 'sand1', hasCollider: true});
blocksMap.set('&',{imageName: 'sand2', hasCollider: true});
blocksMap.set('*',{imageName: 'sand3', hasCollider: true});
blocksMap.set(')',{imageName: 'sand4', hasCollider: true});
blocksMap.set('m',{imageName: 'ground-grass0', hasCollider: true});
blocksMap.set('_',{imageName: 'ground-grass1', hasCollider: true});
blocksMap.set('-',{imageName: 'ground-grass2', hasCollider: true});
blocksMap.set('=',{imageName: 'ground-grass3', hasCollider: true});
blocksMap.set('+',{imageName: 'chest1', hasCollider: false});
blocksMap.set('[',{imageName: 'chest2', hasCollider: false});
blocksMap.set(';',{imageName: 'bed0', hasCollider: false});
blocksMap.set(':',{imageName: 'bed1', hasCollider: false});
blocksMap.set('/',{imageName: 'wall0', hasCollider: false});
blocksMap.set('?',{imageName: 'wall1', hasCollider: false});
blocksMap.set('.',{imageName: 'wall2', hasCollider: false});
export {blocksMap};
